import sys
import json
import httpx
import traceback
from config import config
from services.api import LMSClient
from services.llm import LLMClient
from services.tools import tools

llm = LLMClient()
api = LMSClient()

def get_items(args):
    resp = api.get_items() if hasattr(api, 'get_items') else api._get("items/")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_learners(args):
    resp = api.get_learners() if hasattr(api, 'get_learners') else api._get("learners/")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_scores(args):
    lab = args.get("lab")
    resp = api._get(f"analytics/scores?lab={lab}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_pass_rates(args):
    lab = args.get("lab")
    resp = api._get(f"analytics/pass-rates?lab={lab}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_timeline(args):
    lab = args.get("lab")
    resp = api._get(f"analytics/timeline?lab={lab}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_groups(args):
    lab = args.get("lab")
    resp = api._get(f"analytics/groups?lab={lab}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_top_learners(args):
    lab = args.get("lab")
    limit = args.get("limit", 5)
    resp = api._get(f"analytics/top-learners?lab={lab}&limit={limit}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def get_completion_rate(args):
    lab = args.get("lab")
    resp = api._get(f"analytics/completion-rate?lab={lab}")
    return json.dumps(resp.json()) if resp.status_code == 200 else f"Error: {resp.status_code}"

def trigger_sync(args):
    try:
        resp = httpx.post(f"{api.base_url}/pipeline/sync", headers=api.headers, json={}, timeout=30)
        return "Sync triggered successfully." if resp.status_code == 200 else f"Sync failed: {resp.status_code}"
    except Exception as e:
        return f"Sync error: {e}"

function_map = {
    "get_items": get_items,
    "get_learners": get_learners,
    "get_scores": get_scores,
    "get_pass_rates": get_pass_rates,
    "get_timeline": get_timeline,
    "get_groups": get_groups,
    "get_top_learners": get_top_learners,
    "get_completion_rate": get_completion_rate,
    "trigger_sync": trigger_sync,
}

system_prompt = (
    "You are an AI assistant for an LMS. "
    "CRITICAL INSTRUCTION: When asked to compare multiple labs (e.g., 'lowest pass rate'), "
    "you MUST issue ALL required tool calls SIMULTANEOUSLY in one turn. "
    "DO NOT output conversational filler like 'Let me check' or 'I will continue'. "
    "DO NOT stop early. Always compute and return the FINAL answer with numbers and names."
)

def handle(user_message: str) -> str:
    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_message}
    ]

    max_iterations = 10

    for _ in range(max_iterations):
        try:
            response = llm.chat_completion(messages, tools=tools)
        except Exception as e:
            return f"LLM error: {e}"

        try:
            message = response["choices"][0]["message"]
        except (KeyError, IndexError):
            return "Error: Invalid response format from LLM."

        if not message.get("tool_calls"):
            content = message.get("content", "No content generated by LLM.")
            
            # Анти-лень: если Qwen пытается отмазаться, заставляем его работать дальше
            lower_content = content.lower()
            if "let me" in lower_content or "continue" in lower_content or "checking" in lower_content:
                messages.append(message)
                messages.append({"role": "user", "content": "Do not stop. Execute the tool calls for the remaining labs and give me the final answer."})
                continue
                
            return content

        messages.append(message)
        tool_results = []

        for tool_call in message["tool_calls"]:
            func_name = tool_call["function"]["name"]
            try:
                args = json.loads(tool_call["function"]["arguments"])
            except Exception:
                args = {}

            print(f"[tool] LLM called: {func_name}({args})", file=sys.stderr)

            if func_name in function_map:
                try:
                    result = function_map[func_name](args)
                except Exception as e:
                    result = f"Tool execution error: {str(e)}"
            else:
                result = f"Unknown tool: {func_name}"

            tool_results.append({
                "tool_call_id": tool_call["id"],
                "role": "tool",
                "name": func_name,
                "content": str(result)
            })

        messages.extend(tool_results)

    return "Query too complex, stopped after 10 iterations."

async def handle_telegram(update, context):
    user_message = update.message.text
    try:
        await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
    except Exception:
        pass
    
    try:
        response = handle(user_message)
    except Exception as e:
        response = f"🔥 CRITICAL ROUTER ERROR: {e}"
        print(f"Exception: {e}\n{traceback.format_exc()}", file=sys.stderr)
        
    await update.message.reply_text(response)
